using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ClinicManagementAPI.Models.Responses;
using ClinicManagementAPI.Models.DTOs;

namespace ClinicManagementAPI.Services
{
    public interface IPdfService
    {
        byte[] GeneratePatientHistoryPdf(PatientHistoryResponse patientHistory);
        byte[] GenerateAppointmentHistoryPdf(PatientAppointmentHistoryResponse history);
    }

    public class PdfService : IPdfService
    {
        public PdfService()
        {
            // Set QuestPDF license
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public byte[] GeneratePatientHistoryPdf(PatientHistoryResponse patientHistory)
        {
             var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily(Fonts.SegoeUI));

                    page.Header().Element(ComposeHeader);
                    
                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(20);
                            
                            // Patient Details Box
                            x.Item().Element(c => ComposePatientInfoBox(c, patientHistory.Patient));

                            // Table
                            x.Item().Element(c => ComposeHistoryTable(c, patientHistory.History));
                        });

                    page.Footer().Element(ComposeFooter);
                });
            });

            return document.GeneratePdf();
        }

        public byte[] GenerateAppointmentHistoryPdf(PatientAppointmentHistoryResponse history)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10).FontFamily(Fonts.SegoeUI));

                    page.Header().Element(ComposeHeader);

                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(x =>
                        {
                            x.Spacing(25);

                            // Patient Box
                            x.Item().Element(c => ComposePatientInfoBox(c, history.Patient));

                            // Title for Table Section
                            x.Item().Text("Appointment History").FontSize(14).SemiBold().FontColor(Colors.Grey.Darken3);

                            // Table
                            x.Item().Element(c => ComposeAppointmentTable(c, history.Appointments));
                        });

                    page.Footer().Element(ComposeFooter);
                });
            });

            return document.GeneratePdf();
        }

        // --- Component Composition Methods ---

        void ComposeHeader(IContainer container)
        {
            container.Row(row =>
            {
                row.RelativeItem().Column(column =>
                {
                    column.Item().Text("Clinic Management System").FontSize(20).SemiBold().FontColor(Colors.Blue.Darken2);
                    column.Item().Text("Official Medical Record").FontSize(10).FontColor(Colors.Grey.Medium);
                });

                row.ConstantItem(100).AlignRight().Text(DateTime.Now.ToString("dd MMM yyyy")).SemiBold().FontColor(Colors.Grey.Darken1);
            });
        }

        void ComposeFooter(IContainer container)
        {
            container
                .BorderTop(1)
                .BorderColor(Colors.Grey.Lighten2)
                .PaddingTop(10)
                .Row(row =>
                {
                    row.RelativeItem().Text(x =>
                    {
                        x.Span("Generated by Clinic Management System").FontColor(Colors.Grey.Medium);
                    });
                    
                    row.RelativeItem().AlignRight().Text(x =>
                    {
                        x.CurrentPageNumber();
                        x.Span(" / ");
                        x.TotalPages();
                    });
                });
        }

        // Overload 1: For PatientDto
        void ComposePatientInfoBox(IContainer container, PatientDto? patient)
        {
            if (patient == null) return;

            container
                .Background(Colors.Grey.Lighten5)
                .Padding(15)
                .Border(1)
                .BorderColor(Colors.Grey.Lighten3)
                .Row(row => 
                {
                    row.RelativeItem().Column(col => 
                    {
                        col.Item().Text("Patient Details").FontSize(12).SemiBold().FontColor(Colors.Grey.Darken3).Underline();
                        col.Item().PaddingTop(5).Text(t => 
                        {
                            t.Span("Name: ").SemiBold();
                            t.Span(patient.Name);
                        });
                        col.Item().Text(t =>
                        {
                            t.Span("Age: ").SemiBold();
                            t.Span(patient.Age?.ToString() ?? "N/A");
                        });
                    });

                    row.RelativeItem().Column(col =>
                    {
                        col.Item().Text(""); // Spacer
                        col.Item().PaddingTop(5).Text(t =>
                        {
                            t.Span("Mobile: ").SemiBold();
                            t.Span(patient.Mobile);
                        });
                        col.Item().Text(t =>
                        {
                            t.Span("Email: ").SemiBold();
                            t.Span(patient.Email ?? "N/A");
                        });
                    });
                });
        }

        // Overload 2: For PatientDetailsResponse
        void ComposePatientInfoBox(IContainer container, PatientDetailsResponse? patient)
        {
            if (patient == null) return;

            container
                .Background(Colors.Grey.Lighten5)
                .Padding(15)
                .Border(1)
                .BorderColor(Colors.Grey.Lighten3)
                .Row(row => 
                {
                    row.RelativeItem().Column(col => 
                    {
                        col.Item().Text("Patient Details").FontSize(12).SemiBold().FontColor(Colors.Grey.Darken3).Underline();
                        col.Item().PaddingTop(5).Text(t => 
                        {
                            t.Span("Name: ").SemiBold();
                            t.Span(patient.Name);
                        });
                        col.Item().Text(t =>
                        {
                            t.Span("Age: ").SemiBold();
                            t.Span(patient.Age?.ToString() ?? "N/A");
                        });
                    });

                    row.RelativeItem().Column(col =>
                    {
                        col.Item().Text(""); // Spacer
                        col.Item().PaddingTop(5).Text(t =>
                        {
                            t.Span("Mobile: ").SemiBold();
                            t.Span(patient.Mobile);
                        });
                        col.Item().Text(t =>
                        {
                            t.Span("Email: ").SemiBold();
                            t.Span(patient.Email ?? "N/A");
                        });
                    });
                });
        }

        void ComposeAppointmentTable(IContainer container, List<AppointmentDto> appointments)
        {
            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(70); // Date
                    columns.ConstantColumn(50); // Time
                    columns.RelativeColumn(2);  // Doctor
                    columns.RelativeColumn(2);  // Location
                    columns.RelativeColumn(2);  // Diagnosis
                    columns.RelativeColumn(2);  // Treatment
                    columns.ConstantColumn(70); // Fees
                });

                table.Header(header =>
                {
                    header.Cell().Element(HeaderCellStyle).Text("Date");
                    header.Cell().Element(HeaderCellStyle).Text("Time");
                    header.Cell().Element(HeaderCellStyle).Text("Doctor");
                    header.Cell().Element(HeaderCellStyle).Text("Location");
                    header.Cell().Element(HeaderCellStyle).Text("Diagnosis");
                    header.Cell().Element(HeaderCellStyle).Text("Treatment");
                    header.Cell().Element(HeaderCellStyle).AlignRight().Text("Fees");

                    static IContainer HeaderCellStyle(IContainer container)
                    {
                        return container
                            .Background(Colors.Blue.Darken2)
                            .PaddingVertical(8)
                            .PaddingHorizontal(4)
                            .DefaultTextStyle(x => x.SemiBold().FontColor(Colors.White));
                    }
                });

                var indianCulture = new System.Globalization.CultureInfo("en-IN");

                foreach (var (app, index) in appointments.Select((x, i) => (x, i)))
                {
                    var bgColor = index % 2 == 0 ? Colors.White : Colors.Grey.Lighten5;

                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(app.AppointmentDate);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(app.AppointmentTime);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(app.DoctorName);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(app.LocationName);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(app.Diagnosis ?? "-");
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(app.Treatment ?? "-");
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).AlignRight()
                        .Text(app.Fees?.ToString("C", indianCulture) ?? "-").SemiBold();
                }

                static IContainer BodyCellStyle(IContainer container, string bgColor)
                {
                    return container
                        .Background(bgColor)
                        .BorderBottom(1)
                        .BorderColor(Colors.Grey.Lighten3)
                        .PaddingVertical(8)
                        .PaddingHorizontal(4);
                }
            });
        }

        void ComposeHistoryTable(IContainer container, List<PatientHistoryDto> history)
        {
             container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(80);
                    columns.ConstantColumn(60);
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                });

                table.Header(header =>
                {
                    header.Cell().Element(HeaderCellStyle).Text("Date");
                    header.Cell().Element(HeaderCellStyle).Text("Time");
                    header.Cell().Element(HeaderCellStyle).Text("Doctor");
                    header.Cell().Element(HeaderCellStyle).Text("Diagnosis");
                    header.Cell().Element(HeaderCellStyle).Text("Treatment");
                    header.Cell().Element(HeaderCellStyle).Text("Notes");

                     static IContainer HeaderCellStyle(IContainer container)
                    {
                        return container
                            .Background(Colors.Blue.Darken2)
                            .PaddingVertical(8)
                            .PaddingHorizontal(4)
                            .DefaultTextStyle(x => x.SemiBold().FontColor(Colors.White));
                    }
                });

                foreach (var (visit, index) in history.Select((x, i) => (x, i)))
                {
                    var bgColor = index % 2 == 0 ? Colors.White : Colors.Grey.Lighten5;
                    
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(visit.VisitDate);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(visit.VisitTime);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(visit.DoctorName);
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(visit.Diagnosis ?? "-");
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(visit.Treatment ?? "-");
                    table.Cell().Element(c => BodyCellStyle(c, bgColor)).Text(visit.Notes ?? "-");

                    static IContainer BodyCellStyle(IContainer container, string bgColor)
                    {
                         return container
                            .Background(bgColor)
                            .BorderBottom(1)
                            .BorderColor(Colors.Grey.Lighten3)
                            .PaddingVertical(8)
                            .PaddingHorizontal(4);
                    }
                }
            });
        }
    }
}
